// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl_h8ZBioHaZEaYi1g9Lus6z-L1cOAXF0',
    appId: '1:574055264728:web:82bc8ee078a3fb438082ad',
    messagingSenderId: '574055264728',
    projectId: 'e-commerc-93374',
    authDomain: 'e-commerc-93374.firebaseapp.com',
    storageBucket: 'e-commerc-93374.firebasestorage.app',
    measurementId: 'G-MX7LS109NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCp_tIb9NY9c-Twmo6SoLmK9Wtobg-wvQ',
    appId: '1:574055264728:android:4d9f5a24f81e76118082ad',
    messagingSenderId: '574055264728',
    projectId: 'e-commerc-93374',
    storageBucket: 'e-commerc-93374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rV7-LpO9LmsHEUhbvWvIp8oiRBKLEKk',
    appId: '1:574055264728:ios:ca62b6c07a4f43f38082ad',
    messagingSenderId: '574055264728',
    projectId: 'e-commerc-93374',
    storageBucket: 'e-commerc-93374.firebasestorage.app',
    iosBundleId: 'com.example.elmasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1rV7-LpO9LmsHEUhbvWvIp8oiRBKLEKk',
    appId: '1:574055264728:ios:ca62b6c07a4f43f38082ad',
    messagingSenderId: '574055264728',
    projectId: 'e-commerc-93374',
    storageBucket: 'e-commerc-93374.firebasestorage.app',
    iosBundleId: 'com.example.elmasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl_h8ZBioHaZEaYi1g9Lus6z-L1cOAXF0',
    appId: '1:574055264728:web:7d89e2eaacd706938082ad',
    messagingSenderId: '574055264728',
    projectId: 'e-commerc-93374',
    authDomain: 'e-commerc-93374.firebaseapp.com',
    storageBucket: 'e-commerc-93374.firebasestorage.app',
    measurementId: 'G-K08YQQ46PZ',
  );
}
